version: '3.0'

services:
  db:
    image: postgres:${SOFTWARE_VERSION_TAG_DB}
    restart: always
    container_name: postgresDB
    volumes:
      - ./Database/postgres:/var/lib/postgresql/data
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
  
  pgadmin4:
    image: elestio/pgadmin:${SOFTWARE_VERSION_TAG_PG}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${USER_PG}
      PGADMIN_DEFAULT_PASSWORD: ${PASS_PG}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "${PORT_PG}:8080"
    volumes:
      - ./Database/pgadmin/servers.json:/pgadmin4/servers.json